#!/usr/bin/env bash
# Phase 2 — Hardening + security validation, one command.
# Runs: non-root audit, minimal-image audit, .dockerignore check,
#       Trivy image scans, Gitleaks secret scan, Compose security lint.
# Tools: FOSS only (Trivy + Gitleaks via Docker images, Ubuntu + Docker host).
# Usage:
#   bash scripts/security-scan.sh [--env-file environments/dev.env] [--trivy-severity HIGH,CRITICAL]
# Exit codes: 0 = all gates pass; 1 = lint/secret/non-root gate failed.
#   Trivy findings are REPORTED but do not fail the gate (base-image HIGHs need
#   upstream fixes; remediated dependency CVEs are verified manually). Gitleaks,
#   compose lint, non-root and .dockerignore checks DO gate.
# Runtime stack: Node.js 22 + Express (custom images run as USER node).
set -euo pipefail
cd "$(dirname "$0")/.."

export DOCKER_CONFIG="${DOCKER_CONFIG:-/tmp/docker-nocreds}"
ENV_FILE="environments/dev.env"
SEVERITY="HIGH,CRITICAL"
for arg in "$@"; do
  case "$arg" in
    --env-file=*) ENV_FILE="${arg#*=}" ;;
    --trivy-severity=*) SEVERITY="${arg#*=}" ;;
    environments/*) ENV_FILE="$arg" ;;
  esac
done

PASS=0; FAIL=0
EVIDENCE_DIR="docs/security-evidence"
mkdir -p "$EVIDENCE_DIR"

ok()   { echo "  [PASS] $1"; PASS=$((PASS+1)); }
bad()  { echo "  [FAIL] $1"; FAIL=$((FAIL+1)); }

echo "=== 1/6 non-root audit (Dockerfiles must set an unprivileged USER) ==="
for svc in api ai-service worker ehr-mock alert-logger; do
  df="services/$svc/Dockerfile"
  if grep -qE "^USER (node|appuser)" "$df"; then
    ok "$svc Dockerfile has unprivileged USER ($(grep '^USER' "$df"))"
  else
    bad "$svc Dockerfile missing unprivileged USER"
  fi
done
# Runtime check (only if stack is up; otherwise informational)
for svc in api ai-service worker ehr-mock alert-logger; do
  cname="$(docker compose --env-file "$ENV_FILE" ps -q "$svc" 2>/dev/null || true)"
  if [ -n "$cname" ]; then
    user="$(docker inspect "$cname" --format '{{.Config.User}}' 2>/dev/null || echo '?')"
    if [ "$user" = "node" ] || [ "$user" = "appuser" ]; then ok "$svc runtime user=$user"; else bad "$svc runtime user=$user (want node)"; fi
  else
    echo "  [SKIP] $svc not running — start stack for runtime check"
  fi
done
echo "  NOTE: gateway (nginx:alpine) runs as root by upstream design (master binds :80). Documented in docs/SECURITY.md."

echo ""
echo "=== 2/6 minimal-image audit ==="
for svc in api ai-service worker ehr-mock alert-logger; do
  df="services/$svc/Dockerfile"
  if grep -qiE "apt-get install.*curl|install -y[^&]*curl|curl " "$df"; then
    bad "$svc Dockerfile still installs curl (unnecessary — healthchecks use node fetch)"
  else
    ok "$svc Dockerfile has no curl"
  fi
  if grep -qE "^FROM node:22-slim" "$df"; then
    ok "$svc base image is pinned slim variant ($(grep '^FROM' "$df"))"
  else
    bad "$svc base image is not pinned node slim ($(grep '^FROM' "$df" || echo missing))"
  fi
done
echo "  Image sizes:"
docker images --format "  {{.Repository}}:{{.Tag}} {{.Size}}" 2>/dev/null | grep -E "ai-healthcare|nginx|redis|mongo" || true

echo ""
echo "=== 3/6 .dockerignore check ==="
for svc in api ai-service worker ehr-mock alert-logger; do
  if [ -f "services/$svc/.dockerignore" ]; then
    ok "$svc .dockerignore present"
  else
    bad "$svc .dockerignore MISSING"
  fi
done

echo ""
echo "=== 4/6 Trivy image scans (severity: $SEVERITY) ==="
# Resolve APP_VERSION from env file for accurate tags
APP_VERSION="$(grep -E '^APP_VERSION=' "$ENV_FILE" | cut -d= -f2 || echo 0.1.0-dev)"
for svc in api ai-service worker ehr-mock alert-logger; do
  img="ai-healthcare/$svc:$APP_VERSION"
  out="$EVIDENCE_DIR/trivy-$svc.txt"
  echo "  -- $img -> $out"
  if docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
      -v /tmp/opencode/trivycache:/root/.cache/ \
      aquasec/trivy:latest image --severity "$SEVERITY" --no-progress "$img" >"$out" 2>&1; then
    # trivy exits 0 unless --exit-code set; summarize totals
    total="$(grep -E '^Total:' "$out" | tr '\n' '; ' || echo 'n/a')"
    echo "     $total"
    ok "trivy scan completed for $svc ($total)"
  else
    bad "trivy scan failed for $svc (see $out)"
  fi
done
echo "  Full reports: $EVIDENCE_DIR/trivy-*.txt"

echo ""
echo "=== 5/6 Gitleaks secret scan (git mode when .git exists, else --no-git) ==="
# Phase 3 fix: remove the stale report BEFORE scanning. Gitleaks `-v` output embeds
# matched secret text, so a previous FAIL report left on disk would re-detect its
# own embedded snippets on the next run (self-contamination). The report is
# regenerated by this step, so deleting the stale copy loses nothing.
rm -f "$EVIDENCE_DIR/gitleaks.txt"
# P0.1: repo now has git history — prefer git mode (scans tracked diffs +
# history); fall back to --no-git only outside a checkout.
GITLEAKS_ARGS="detect --source=/repo -v"
if [ -d .git ]; then
  echo "  (git mode: .git present)"
else
  echo "  (fallback --no-git: no .git found)"
  GITLEAKS_ARGS="detect --source=/repo --no-git -v"
fi
if docker run --rm -v "$(pwd):/repo" zricethezav/gitleaks:latest $GITLEAKS_ARGS >"$EVIDENCE_DIR/gitleaks.txt" 2>&1; then
  ok "gitleaks: no leaks found (see $EVIDENCE_DIR/gitleaks.txt)"
else
  bad "gitleaks found leaks or errored (see $EVIDENCE_DIR/gitleaks.txt)"
  tail -20 "$EVIDENCE_DIR/gitleaks.txt" || true
fi

echo ""
echo "=== 6/6 Compose security lint ==="
python3 scripts/compose-lint.py --compose-file docker-compose.yml --evidence "$EVIDENCE_DIR/compose-lint.txt" \
  && ok "compose lint passed (see $EVIDENCE_DIR/compose-lint.txt)" \
  || bad "compose lint failed (see $EVIDENCE_DIR/compose-lint.txt)"
cat "$EVIDENCE_DIR/compose-lint.txt"

echo ""
echo "==================================="
echo "RESULT: $PASS passed, $FAIL failed"
if [ "$FAIL" -gt 0 ]; then echo "SECURITY SCAN: FAIL"; exit 1; else echo "SECURITY SCAN: PASS"; fi
